version: "3.7"

services:
  angular-frontend:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.staging
    image: angular-frontend-staging-env
    container_name: angular-frontend-staging-env
    restart: always
    ports:
      - "80"
    networks:
      - pulpo_line_network

networks:
  traefik_network:
    external: true